### ISSUE TITLE
On Viomi, sound page doesn't display set sound level. 

### ISSUE THREAD

**Issue by Kaan88** [Hypfer/Valetudo#1062]
## Describe the bug

When you enter the page it's stuck on loading animation. But it's a small issue because the main functionality works fine.
### Vacuum Model

Viomi v6 (converted from v8)
### Valetudo Version

2021.8.1

## Expected behavior

It should display set sound level.
## Additional context

    [2021-08-31T12:07:46.771Z] [ERROR] unhandledRejection {
      reason: TypeError: amixer.stdout.matchAll is not a function
          at ViomiSpeakerVolumeControlCapability.getAlsaVolume (/snapshot/Valetudo/backend/lib/robots/common/linuxCapabilities/LinuxAlsaSpeakerVolumeControlCapability.js:81:38)
          at ViomiSpeakerVolumeControlCapability.getVolume (/snapshot/Valetudo/backend/lib/robots/common/linuxCapabilities/LinuxAlsaSpeakerVolumeControlCapability.js:164:21)
          at ViomiSpeakerVolumeControlCapability.getVolume (/snapshot/Valetudo/backend/lib/robots/viomi/capabilities/ViomiSpeakerVolumeControlCapability.js:14:32)
          at /snapshot/Valetudo/backend/lib/webserver/capabilityRouters/SpeakerVolumeControlCapabilityRouter.js:9:47
          at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)
          at next (/snapshot/Valetudo/node_modules/express/lib/router/route.js:137:13)
          at Route.dispatch (/snapshot/Valetudo/node_modules/express/lib/router/route.js:112:3)
          at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)
          at /snapshot/Valetudo/node_modules/express/lib/router/index.js:281:22
          at Function.process_params (/snapshot/Valetudo/node_modules/express/lib/router/index.js:335:12)
          at next (/snapshot/Valetudo/node_modules/express/lib/router/index.js:275:10)
          at Function.handle (/snapshot/Valetudo/node_modules/express/lib/router/index.js:174:3)
          at router (/snapshot/Valetudo/node_modules/express/lib/router/index.js:47:12)
          at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)
          at trim_prefix (/snapshot/Valetudo/node_modules/express/lib/router/index.js:317:13)
          at /snapshot/Valetudo/node_modules/express/lib/router/index.js:284:7,
      stack: 'TypeError: amixer.stdout.matchAll is not a function\n' +
        '    at ViomiSpeakerVolumeControlCapability.getAlsaVolume (/snapshot/Valetudo/backend/lib/robots/common/linuxCapabilities/LinuxAlsaSpeakerVolumeControlCapability.js:81:38)\n' +
        '    at ViomiSpeakerVolumeControlCapability.getVolume (/snapshot/Valetudo/backend/lib/robots/common/linuxCapabilities/LinuxAlsaSpeakerVolumeControlCapability.js:164:21)\n' +
        '    at ViomiSpeakerVolumeControlCapability.getVolume (/snapshot/Valetudo/backend/lib/robots/viomi/capabilities/ViomiSpeakerVolumeControlCapability.js:14:32)\n' +
        '    at /snapshot/Valetudo/backend/lib/webserver/capabilityRouters/SpeakerVolumeControlCapabilityRouter.js:9:47\n' +
        '    at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)\n' +
        '    at next (/snapshot/Valetudo/node_modules/express/lib/router/route.js:137:13)\n' +
        '    at Route.dispatch (/snapshot/Valetudo/node_modules/express/lib/router/route.js:112:3)\n' +
        '    at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)\n' +
        '    at /snapshot/Valetudo/node_modules/express/lib/router/index.js:281:22\n' +
        '    at Function.process_params (/snapshot/Valetudo/node_modules/express/lib/router/index.js:335:12)\n' +
        '    at next (/snapshot/Valetudo/node_modules/express/lib/router/index.js:275:10)\n' +
        '    at Function.handle (/snapshot/Valetudo/node_modules/express/lib/router/index.js:174:3)\n' +
        '    at router (/snapshot/Valetudo/node_modules/express/lib/router/index.js:47:12)\n' +
        '    at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)\n' +
        '    at trim_prefix (/snapshot/Valetudo/node_modules/express/lib/router/index.js:317:13)\n' +
        '    at /snapshot/Valetudo/node_modules/express/lib/router/index.js:284:7',
      promise: Promise {
        <rejected> TypeError: amixer.stdout.matchAll is not a function
            at ViomiSpeakerVolumeControlCapability.getAlsaVolume (/snapshot/Valetudo/backend/lib/robots/common/linuxCapabilities/LinuxAlsaSpeakerVolumeControlCapability.js:81:38)
            at ViomiSpeakerVolumeControlCapability.getVolume (/snapshot/Valetudo/backend/lib/robots/common/linuxCapabilities/LinuxAlsaSpeakerVolumeControlCapability.js:164:21)
            at ViomiSpeakerVolumeControlCapability.getVolume (/snapshot/Valetudo/backend/lib/robots/viomi/capabilities/ViomiSpeakerVolumeControlCapability.js:14:32)
            at /snapshot/Valetudo/backend/lib/webserver/capabilityRouters/SpeakerVolumeControlCapabilityRouter.js:9:47
            at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)
            at next (/snapshot/Valetudo/node_modules/express/lib/router/route.js:137:13)
            at Route.dispatch (/snapshot/Valetudo/node_modules/express/lib/router/route.js:112:3)
            at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)
            at /snapshot/Valetudo/node_modules/express/lib/router/index.js:281:22
            at Function.process_params (/snapshot/Valetudo/node_modules/express/lib/router/index.js:335:12)
            at next (/snapshot/Valetudo/node_modules/express/lib/router/index.js:275:10)
            at Function.handle (/snapshot/Valetudo/node_modules/express/lib/router/index.js:174:3)
            at router (/snapshot/Valetudo/node_modules/express/lib/router/index.js:47:12)
            at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)
            at trim_prefix (/snapshot/Valetudo/node_modules/express/lib/router/index.js:317:13)
            at /snapshot/Valetudo/node_modules/express/lib/router/index.js:284:7
      }
    }

**Comment by Kaan88** [comment]
Fixed by https://github.com/Hypfer/Valetudo/pull/1214
