### ISSUE TITLE
Viomi V7 memory overflow

### ISSUE THREAD

**Issue by Omrigan** [Hypfer/Valetudo#1249]
## Describe the bug
Valetudo spontaneously shuts down with a following error message:

> Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]: [2021-11-27T03:55:25.221Z] [ERROR] Valetudo is currently taking up 179138560 bytes which is more than 1/3 of available system memory. To ensure safe robot operation, it will now shutdown.
 

## To Reproduce
Just leave it as it is. In my case it happens i n 2-4 hours after I `/etc/init.d/valetudo restart`

### Vacuum Model
Viomi V7

### Valetudo Version
2021.11.0 

arm7-lowmem binary

## Expected behavior
Not crash

## Additional context

Full log here. 

<details>
  <summary>valetudo.log</summary>

```
Sat Nov 27 03:26:37 2021 daemon.err valetudo[702]: [2021-11-27T03:26:37.480Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:27:08 2021 daemon.err valetudo[702]: [2021-11-27T03:27:08.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:27:38 2021 daemon.err valetudo[702]: [2021-11-27T03:27:38.480Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:28:09 2021 daemon.err valetudo[702]: [2021-11-27T03:28:09.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:28:39 2021 daemon.err valetudo[702]: [2021-11-27T03:28:39.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:29:09 2021 daemon.err valetudo[702]: [2021-11-27T03:29:09.480Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:29:39 2021 daemon.err valetudo[702]: [2021-11-27T03:29:39.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:30:10 2021 daemon.err valetudo[702]: [2021-11-27T03:30:10.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:30:40 2021 daemon.err valetudo[702]: [2021-11-27T03:30:40.804Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:31:11 2021 daemon.err valetudo[702]: [2021-11-27T03:31:11.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:31:41 2021 daemon.err valetudo[702]: [2021-11-27T03:31:41.671Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:32:12 2021 daemon.err valetudo[702]: [2021-11-27T03:32:12.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:32:42 2021 daemon.err valetudo[702]: [2021-11-27T03:32:42.492Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:33:13 2021 daemon.err valetudo[702]: [2021-11-27T03:33:13.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:33:43 2021 daemon.err valetudo[702]: [2021-11-27T03:33:43.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:34:13 2021 daemon.err valetudo[702]: [2021-11-27T03:34:13.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:34:43 2021 daemon.err valetudo[702]: [2021-11-27T03:34:43.485Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:35:14 2021 daemon.err valetudo[702]: [2021-11-27T03:35:14.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:35:44 2021 daemon.err valetudo[702]: [2021-11-27T03:35:44.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:36:15 2021 daemon.err valetudo[702]: [2021-11-27T03:36:15.480Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:36:45 2021 daemon.err valetudo[702]: [2021-11-27T03:36:45.480Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:37:16 2021 daemon.err valetudo[702]: [2021-11-27T03:37:16.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:37:46 2021 daemon.err valetudo[702]: [2021-11-27T03:37:46.516Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:38:17 2021 daemon.err valetudo[702]: [2021-11-27T03:38:17.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:38:47 2021 daemon.err valetudo[702]: [2021-11-27T03:38:47.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:39:17 2021 daemon.err valetudo[702]: [2021-11-27T03:39:17.494Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:39:47 2021 daemon.err valetudo[702]: [2021-11-27T03:39:47.480Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:40:18 2021 daemon.err valetudo[702]: [2021-11-27T03:40:18.480Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:40:48 2021 daemon.err valetudo[702]: [2021-11-27T03:40:48.480Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:41:19 2021 daemon.err valetudo[702]: [2021-11-27T03:41:19.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:41:49 2021 daemon.err valetudo[702]: [2021-11-27T03:41:49.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:42:20 2021 daemon.err valetudo[702]: [2021-11-27T03:42:20.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:42:50 2021 daemon.err valetudo[702]: [2021-11-27T03:42:50.677Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:43:20 2021 daemon.err valetudo[702]: [2021-11-27T03:43:20.499Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:43:50 2021 daemon.err valetudo[702]: [2021-11-27T03:43:50.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:44:21 2021 daemon.err valetudo[702]: [2021-11-27T03:44:21.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:44:51 2021 daemon.err valetudo[702]: [2021-11-27T03:44:51.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:45:22 2021 daemon.err valetudo[702]: [2021-11-27T03:45:22.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:45:52 2021 daemon.err valetudo[702]: [2021-11-27T03:45:52.719Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:46:23 2021 daemon.err valetudo[702]: [2021-11-27T03:46:23.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:46:53 2021 daemon.err valetudo[702]: [2021-11-27T03:46:53.607Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:47:24 2021 daemon.err valetudo[702]: [2021-11-27T03:47:24.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:47:54 2021 daemon.err valetudo[702]: [2021-11-27T03:47:54.521Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:48:05 2021 daemon.info udhcpc[864]: Sending renew...
Sat Nov 27 03:48:05 2021 daemon.info udhcpc[864]: Lease of 192.168.3.100 obtained, lease time 43200
Sat Nov 27 03:48:22 2021 daemon.info valetudo[702]: [2021-11-27T03:48:22.317Z] [INFO] Unknown cloud message received: {"id":34667077,"method":"_otc.ncinfo","params":{"miio_ver":"0.0.5","miio_times":[21619,-1,0,21585],"ot_stat":[1,0,1],"otu_stat":[1,0,-1,183,7,93,108,61,47],"ott_stat":[0,0,-1,-1,-1,-1,0,0,0]}}
Sat Nov 27 03:48:22 2021 daemon.info valetudo[702]: [2021-11-27T03:48:22.322Z] [INFO] Unknown cloud message received: {"method":"_otc.ncstat","id":107656396,"params":{"timestamp":1637983102,"proto":0,"otip":"127.0.0.1","otport":8053,"sendcnt":5,"ackcnt":5,"ackcnt_timeout":0,"costtime":39,"rpc":180,"rpcack":180,"rpc_local":0,"rpcack_local":0,"dns":1,"keepalive_interval":20}}
Sat Nov 27 03:48:25 2021 daemon.err valetudo[702]: [2021-11-27T03:48:25.488Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:48:55 2021 daemon.err valetudo[702]: [2021-11-27T03:48:55.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:49:25 2021 daemon.err valetudo[702]: [2021-11-27T03:49:25.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:49:55 2021 daemon.err valetudo[702]: [2021-11-27T03:49:55.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:50:26 2021 daemon.err valetudo[702]: [2021-11-27T03:50:26.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:50:56 2021 daemon.err valetudo[702]: [2021-11-27T03:50:56.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:51:27 2021 daemon.err valetudo[702]: [2021-11-27T03:51:27.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:51:57 2021 daemon.err valetudo[702]: [2021-11-27T03:51:57.679Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:52:28 2021 daemon.err valetudo[702]: [2021-11-27T03:52:28.485Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:52:58 2021 daemon.err valetudo[702]: [2021-11-27T03:52:58.673Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:53:29 2021 daemon.err valetudo[702]: [2021-11-27T03:53:29.485Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:53:59 2021 daemon.err valetudo[702]: [2021-11-27T03:53:59.479Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:54:29 2021 daemon.err valetudo[702]: [2021-11-27T03:54:29.481Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:54:59 2021 daemon.err valetudo[702]: [2021-11-27T03:54:59.486Z] [WARN] Error while adjusting timezone to UTC
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]: [2021-11-27T03:55:25.221Z] [ERROR] Valetudo is currently taking up 179138560 bytes which is more than 1/3 of available system memory. To ensure safe robot operation, it will now shutdown.
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:  {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:   'process.memoryUsage()': {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     rss: 177090560,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     heapTotal: 32509952,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     heapUsed: 28029468,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     external: 127763288,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     arrayBuffers: 124503765
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:   },
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:   'process.resourceUsage()': {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     userCPUTime: 4990810000,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     systemCPUTime: 98890000,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     maxRSS: 175520,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     sharedMemorySize: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     unsharedDataSize: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     unsharedStackSize: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     minorPageFault: 3784309,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     majorPageFault: 171,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     swappedOut: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     fsRead: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     fsWrite: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     ipcSent: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     ipcReceived: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     signalsCount: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     voluntaryContextSwitches: 312194,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     involuntaryContextSwitches: 816149
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:   },
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:   'v8.getHeapStatistics()': {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     total_heap_size: 32509952,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     total_heap_size_executable: 262144,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     total_physical_size: 32252108,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     total_available_size: 5210180,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     used_heap_size: 28036624,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     heap_size_limit: 35651584,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     malloced_memory: 270380,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     peak_malloced_memory: 2483296,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     does_zap_garbage: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     number_of_native_contexts: 1,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     number_of_detached_contexts: 0
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:   },
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:   'v8.getHeapSpaceStatistics()': [
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_name: 'read_only_space',
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_size: 135168,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_used_size: 123832,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_available_size: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       physical_space_size: 135168
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     },
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_name: 'old_space',
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_size: 22331392,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_used_size: 20428360,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_available_size: 700,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       physical_space_size: 22219692
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     },
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_name: 'code_space',
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_size: 77824,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_used_size: 55680,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_available_size: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       physical_space_size: 72064
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     },
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_name: 'map_space',
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_size: 1060864,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_used_size: 772808,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_available_size: 45040,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       physical_space_size: 921120
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     },
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_name: 'large_object_space',
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_size: 6807552,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_used_size: 6648288,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_available_size: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       physical_space_size: 6807552
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     },
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_name: 'code_large_object_space',
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_size: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_used_size: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_available_size: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       physical_space_size: 0
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     },
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_name: 'new_large_object_space',
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_size: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_used_size: 0,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_available_size: 1015232,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       physical_space_size: 0
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     },
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_name: 'new_space',
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_size: 2097152,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_used_size: 12760,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       space_available_size: 1002472,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:       physical_space_size: 2097128
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     }
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:   ],
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:   'v8.getHeapCodeStatistics()': {
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     code_and_metadata_size: 69600,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     bytecode_and_metadata_size: 287168,
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:     external_script_source_size: 1945206
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]:   }
Sat Nov 27 03:55:25 2021 daemon.err valetudo[702]: }
Sat Nov 27 03:55:25 2021 daemon.info valetudo[702]: [2021-11-27T03:55:25.260Z] [INFO] Valetudo shutdown in progress...
Sat Nov 27 03:55:30 2021 daemon.err valetudo[702]: [2021-11-27T03:55:30.262Z] [WARN] Failed to shutdown valetudo in a timely manner. Using (the) force
Sat Nov 27 03:55:30 2021 daemon.err valetudo[702]: [2021-11-27T03:55:30.267Z] [ERROR] Stacktrace that lead to the process exiting with code 1: Error
Sat Nov 27 03:55:30 2021 daemon.err valetudo[702]:     at process.<anonymous> (/snapshot/Valetudo/backend/index.js:48:93)
Sat Nov 27 03:55:30 2021 daemon.err valetudo[702]:     at process.emit (node:events:390:28)
Sat Nov 27 03:55:30 2021 daemon.err valetudo[702]:     at process.exit (node:internal/process/per_thread:184:15)
Sat Nov 27 03:55:30 2021 daemon.err valetudo[702]:     at Timeout._onTimeout (/snapshot/Valetudo/backend/lib/Valetudo.js:191:21)
Sat Nov 27 03:55:30 2021 daemon.err valetudo[702]:     at listOnTimeout (node:internal/timers:557:17)
Sat Nov 27 03:55:30 2021 daemon.err valetudo[702]:     at processTimers (node:internal/timers:500:7)
Sat Nov 27 09:48:05 2021 daemon.info udhcpc[864]: Sending renew...
Sat Nov 27 09:48:05 2021 daemon.info udhcpc[864]: Lease of 192.168.3.100 obtained, lease time 43200
Sat Nov 27 13:38:00 2021 authpriv.info dropbear[2536]: Child connection from 192.168.3.1:59564
Sat Nov 27 13:38:00 2021 authpriv.notice dropbear[2536]: Pubkey auth succeeded for 'root' with key md5 15:4c:6b:4a:47:38:1b:66:d0:e2:79:8c:2e:8c:d5:c7 from 192.168.3.1:59564
Sat Nov 27 13:38:30 2021 authpriv.info dropbear[2536]: Exit (root): Disconnect received
Sat Nov 27 13:38:33 2021 authpriv.info dropbear[2546]: Child connection from 192.168.3.1:59570
Sat Nov 27 13:38:33 2021 authpriv.notice dropbear[2546]: Pubkey auth succeeded for 'root' with key md5 15:4c:6b:4a:47:38:1b:66:d0:e2:79:8c:2e:8c:d5:c7 from 192.168.3.1:59570
Sat Nov 27 13:38:33 2021 authpriv.info dropbear[2546]: Exit (root): Disconnect received
Sat Nov 27 13:38:41 2021 authpriv.info dropbear[2549]: Child connection from 192.168.3.1:59572
Sat Nov 27 13:38:41 2021 authpriv.notice dropbear[2549]: Pubkey auth succeeded for 'root' with key md5 15:4c:6b:4a:47:38:1b:66:d0:e2:79:8c:2e:8c:d5:c7 from 192.168.3.1:59572
```
</details>

<details>
  <summary>Top processes after restarting valetudo</summary>

```
$ ps -o pid,user,%mem,command ax   | sort -b -k3 -r  | head
 PID USER     %MEM COMMAND
 2602 root      8.6 /mnt/UDISK/valetudo
  620 root      6.0 RobotApp
  657 root      5.2 everest-server
  631 root      1.0 AuxCtrl
  683 root      0.3 /usr/sbin/upgrade -D
  675 root      0.3 log-server
  600 root      0.2 /usr/sbin/Monitor -D
  768 root      0.1 wpa_supplicant -dd -iwlan0 -Dnl80211 -c/etc/wifi/wpa_supplicant.conf
    1 root      0.1 /sbin/procd
```
</details>

**Comment by Omrigan** [comment]
Temporarily disabled MQTT, seems to "fix" the issue. 

>Valetudo is currently taking up 179138560 bytes which is more than 1/3 of available system memory. To ensure safe robot operation, it will now shutdown.

Maybe we should have an option like what share of my memory I am willing to give to valetudo. Maybe if it is tweaked to 1/2, robot would still work.

**Comment by Hypfer** [comment]
Did this ever happen with newer versions of valetudo?

**Comment by Omrigan** [comment]
I've been using 2022.02 version for several days now, everything seems to be alright.

I'll reopen the issue if I encounter problems again.

Thanks for the fix!
