### ISSUE TITLE
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by adminy** [Hypfer/Valetudo#1368]
## Describe the bug
The backend seems to be failing with internal server error 500.
## To Reproduce
1. Go to 'http://192.168.8.114/'
2. Open dev console
3. See error

### Screenshots

![Screenshot 2022-01-21 at 22 49 13](https://user-images.githubusercontent.com/22717869/150610485-fe491045-43b2-4cd1-bdd5-391eb58a8064.png)

### Vacuum Model
Roborock S7

### Valetudo Version
2022.01.0

## Expected behavior
It should just work right?

## Additional context
I just followed the instructions from https://dontvacuum.me/

in one of the 500 requests found:
```
"request timed out:{\"method\":\"get_status\",\"params\":{}}"
```

**Comment by adminy** [comment]
Why?

**Comment by adminy** [comment]
valetudo.log
```log
[2022-01-22T10:31:40.831Z] [INFO] Current rootfs: system_a (nande)
[2022-01-22T10:31:58.724Z] [INFO] Valetudo can be reached via: valetudo-welcomeincompatiblelocust.local
[2022-01-22T10:31:58.759Z] [INFO] Setting /proc/self/oom_score_adj to 666. Previous value: 0
[2022-01-22T10:31:58.776Z] [INFO] Dummycloud is spoofing 127.0.0.1:8053 on 127.0.0.1:8053
[2022-01-22T10:31:58.778Z] [INFO] Webserver running on port 80
[2022-01-22T10:31:58.790Z] [INFO] SSDP/UPnP advertisement started
[2022-01-22T10:31:58.805Z] [INFO] Map Upload Server running on port 8079
[2022-01-22T10:31:58.829Z] [INFO] Bonjour service "Valetudo S7 Web" with type "http" started
[2022-01-22T10:31:58.832Z] [INFO] Bonjour service "Valetudo S7" with type "valetudo" started
[2022-01-22T10:32:03.003Z] [INFO] Successfully set the robot time via NTP to 2022-01-22T10:32:03.896Z
[2022-01-22T10:50:03.759Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:03.772Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:03.775Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:03.778Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:03.780Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:03.783Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:03.786Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:03.789Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:03.791Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:03.794Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:03.796Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:03.818Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:03.821Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:03.824Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:03.827Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:03.829Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:03.831Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:03.834Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:03.836Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:03.839Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:03.841Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:03.842Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:03.892Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:03.896Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:03.898Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:03.900Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:03.903Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:03.905Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:03.907Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:03.909Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:03.911Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:03.913Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:03.915Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:03.915Z] [WARN] Error while fetching statistics MiioTimeoutError: request timed out:{"method":"get_status","params":{}}
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:126:23)
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:155:25)
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:155:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-01-22T10:50:04.824Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:04.829Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:04.833Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:04.837Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:04.841Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:04.844Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:04.848Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:04.852Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:04.855Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:04.859Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:04.861Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:04.876Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:04.880Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:04.884Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:04.887Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:04.890Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:04.894Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:04.904Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:04.908Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:04.911Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:04.915Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:04.916Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:04.946Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:04.951Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:04.954Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:04.958Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:04.961Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:04.964Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:04.968Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:04.971Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:04.974Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:04.978Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:04.979Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:04.981Z] [WARN] Error while fetching statistics MiioTimeoutError: request timed out:{"method":"get_status","params":{}}
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:126:23)
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:155:25)
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:155:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-01-22T10:50:06.925Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:06.930Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:06.934Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:06.944Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:06.948Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:06.952Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:06.955Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:06.959Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:06.962Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:06.966Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:06.967Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:06.988Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:06.993Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:06.997Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:07.001Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:07.005Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:07.009Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:07.012Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:07.016Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:07.019Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:07.023Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:07.025Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:07.040Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:07.045Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:07.048Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:07.052Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:07.055Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:07.059Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:07.062Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:07.065Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:07.069Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:07.072Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:07.073Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:07.075Z] [WARN] Error while fetching statistics MiioTimeoutError: request timed out:{"method":"get_status","params":{}}
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:126:23)
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:155:25)
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:155:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
[2022-01-22T10:50:11.021Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:11.026Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:11.031Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:11.035Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:11.038Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:11.042Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:11.051Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:11.055Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:11.059Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:11.062Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:11.064Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:11.080Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:11.084Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:11.088Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:11.091Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:11.095Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:11.098Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:11.102Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:11.106Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:11.109Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:11.112Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:11.114Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:11.130Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 10, method: 'get_status', args: {} }
[2022-01-22T10:50:11.135Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 20, method: 'get_status', args: {} }
[2022-01-22T10:50:11.139Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 30, method: 'get_status', args: {} }
[2022-01-22T10:50:11.142Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 40, method: 'get_status', args: {} }
[2022-01-22T10:50:11.145Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 50, method: 'get_status', args: {} }
[2022-01-22T10:50:11.149Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 60, method: 'get_status', args: {} }
[2022-01-22T10:50:11.152Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 70, method: 'get_status', args: {} }
[2022-01-22T10:50:11.155Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 80, method: 'get_status', args: {} }
[2022-01-22T10:50:11.158Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 90, method: 'get_status', args: {} }
[2022-01-22T10:50:11.162Z] [WARN] Token is okay, however we're unable to reach the vacuum { retries: 100, method: 'get_status', args: {} }
[2022-01-22T10:50:11.163Z] [ERROR] Unable to reach vacuum. Giving up after 100 tries
[2022-01-22T10:50:11.164Z] [WARN] Error while fetching statistics MiioTimeoutError: request timed out:{"method":"get_status","params":{}}
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:126:23)
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:155:25)
    at RetryWrapper.sendMessage (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:155:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by adminy** [comment]
The solution to this issue:

`sed '/^cfg_by=.*$/=miot/' /mnt/data/miio/wifi.conf`

and then run `echo -n 'de' > /mnt/data/miio/device.country`
