### ISSUE TITLE
Update not possible from 2022.01 to 2022.02

### ISSUE THREAD

**Issue by buarle** [Hypfer/Valetudo#1380]
## Describe the bug
Update not possible from 2022.01 to 2022.02

## To Reproduce
Click update via the Front End

### Screenshots
2022-01-28T13:07:46.681Z
Error
Error while downloading release binary TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:119:11)
    at Url.parse (node:url:169:3)
    at Object.urlParse [as parse] (node:url:156:13)
    at dispatchHttpRequest (/snapshot/Valetudo/node_modules/axios/lib/adapters/http.js:118:22)
    at new Promise (<anonymous>)
    at httpAdapter (/snapshot/Valetudo/node_modules/axios/lib/adapters/http.js:48:10)
    at dispatchRequest (/snapshot/Valetudo/node_modules/axios/lib/core/dispatchRequest.js:58:10)
    at Axios.request (/snapshot/Valetudo/node_modules/axios/lib/core/Axios.js:108:15)
    at Axios.<computed> [as get] (/snapshot/Valetudo/node_modules/axios/lib/core/Axios.js:129:17)
    at Function.wrap [as get] (/snapshot/Valetudo/node_modules/axios/lib/helpers/bind.js:9:15)
    at Updater.download (/snapshot/Valetudo/backend/lib/updater/Updater.js:136:50)
    at Updater.triggerDownload (/snapshot/Valetudo/backend/lib/updater/Updater.js:89:14)
    at /snapshot/Valetudo/backend/lib/webserver/UpdaterRouter.js:37:42
    at Layer.handle [as handle_request] (/snapshot/Valetudo/node_modules/express/lib/router/layer.js:95:5)
    at next (/snapshot/Valetudo/node_modules/express/lib/router/route.js:137:13) {
  code: 'ERR_INVALID_ARG_TYPE'
}

### Vacuum Model
Roborock S5

### Valetudo Version
2022.01

## Expected behavior
Updateing to new version

**Comment by Hypfer** [comment]
Looks like you're running a broken binary. There was a _very_ short time where the 2022.01.0 was broken like this
It has been fixed and only affected ~10 people iirc. Apparently, you're one of them.

Please follow the instructions at https://valetudo.cloud/pages/general/upgrading.html

**Comment by buarle** [comment]
Hi @Hypfer ,

unlucky but never mind. Already creating the image.

Thanks for your work man!

Best
buarle

**Comment by ManuelW77** [comment]
Damn, so i'm the second one with this problem :D
