### ISSUE TITLE
Dreame Z10Pro: Log shows Warning about serialization of Quirks

### ISSUE THREAD

**Issue by coderph0x** [Hypfer/Valetudo#1390]
## Describe the bug
After updating my Z10 Pro to 2022.02 the log shows a warning about serialization of the Quirks.

## To Reproduce
1. Open Quirks section
2. Open Log
3. Discover warning

### Vacuum Model

Dreame Z10Pro

### Valetudo Version

2022.02

## Expected behavior
There probably shouldn't be a warning.

## Additional information
Log entry:
```
2022-01-31T14:54:14.377Z
Warn
Error while serializing quirk with ID 8471c118-f1e1-4866-ad2e-3c11865a5ba8 Error: Error code -1
    at DreameMiotHelper.readProperty (/snapshot/Valetudo/backend/lib/robots/dreame/DreameMiotHelper.js:29:23)
    at async Quirk.getter (/snapshot/Valetudo/backend/lib/robots/dreame/DreameQuirkFactory.js:74:37)
    at async Quirk.serialize (/snapshot/Valetudo/backend/lib/core/Quirk.js:44:20)
```

**Comment by Hypfer** [comment]
That's the `TIGHT_MOP_PATTERN` quirk.
You're likely running a firmware version that is too old to feature that.


You can either just ignore that warning or upgrade to a newer firmware
