### ISSUE TITLE
"Error loading basic controls" after fresh install

### ISSUE THREAD

**Issue by adaasch** [Hypfer/Valetudo#1478]
## Describe the bug

Valetudo seems not to connect to the robot. Rest seems to work.

## To Reproduce

- New Dreame D9 
- Successful "root" and installation with dustbuilder 
- Open Webapp

- Several reboots didn't help
- Connection to home wifi works

### Screenshots

![image](https://user-images.githubusercontent.com/11362267/165461693-b61776d0-da32-488d-a130-4cebc85e8c90.png)

### Vacuum Model

Dreame D9

### Valetudo Version

2022.03.1

## Expected behavior

Valetudo should be able to control the robot

## Additional context

Log: 
```
[1970-01-01T00:56:15.169Z] [INFO] Set Logfile to /tmp/valetudo.log
[1970-01-01T00:56:15.190Z] [INFO] Autodetected DreameD9ValetudoRobot
[1970-01-01T00:56:15.320Z] [INFO] Starting Valetudo 2022.03.1
[1970-01-01T00:56:15.322Z] [INFO] Commit ID: 166c69d87fc9b1fd2010e0787ad1c68ab71710ea
[1970-01-01T00:56:15.322Z] [INFO] Configuration file: /data/valetudo_config.json
[1970-01-01T00:56:15.323Z] [INFO] Logfile: /tmp/valetudo.log
[1970-01-01T00:56:15.324Z] [INFO] Robot: Dreame D9 (DreameD9ValetudoRobot)
[1970-01-01T00:56:15.324Z] [INFO] JS Runtime Version: v16.10.0
[1970-01-01T00:56:15.325Z] [INFO] Arch: arm
[1970-01-01T00:56:15.326Z] [INFO] Max Heap Size: 34 MiB
[1970-01-01T00:56:15.327Z] [INFO] Node Flags: --expose-gc --max-heap-size=34 --optimize-for-size --lite-mode --no-regexp-tier-up --no-expose-wasm
[1970-01-01T00:56:15.346Z] [INFO] Autogenerated System ID: PaleCleanSparrow
[1970-01-01T00:56:15.350Z] [INFO] DeviceId 520954959
[1970-01-01T00:56:15.351Z] [INFO] IP 127.0.0.1
[1970-01-01T00:56:15.351Z] [INFO] CloudSecret pA288H32zjl8KKU3
[1970-01-01T00:56:15.352Z] [INFO] LocalSecret FCRc1iYvEw80X9OL
[1970-01-01T00:56:15.354Z] [INFO] Firmware Version: 1100
[1970-01-01T00:56:15.354Z] [INFO] MCU Version: 0.9.1
[1970-01-01T00:56:15.360Z] [INFO] Current rootfs: rootfs1 (/dev/nand0p4)
[1970-01-01T00:56:16.430Z] [INFO] Valetudo can be reached via: valetudo-palecleansparrow.local
[1970-01-01T00:56:32.194Z] [INFO] Setting /proc/self/oom_score_adj to 666. Previous value: 0
[1970-01-01T00:56:32.210Z] [INFO] Dummycloud is spoofing 127.0.0.1:8053 on 127.0.0.1:8053
[1970-01-01T00:56:32.232Z] [INFO] Webserver running on port 80
[1970-01-01T00:56:32.239Z] [INFO] FDSMockServer running on port 8079
[1970-01-01T00:56:32.262Z] [INFO] Bonjour service "Valetudo D9 Web" with type "http" started
[1970-01-01T00:56:32.263Z] [INFO] Bonjour service "Valetudo D9" with type "valetudo" started
[1970-01-01T00:56:32.296Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[1970-01-01T00:56:32.350Z] [INFO] Connected successfully to MQTT broker
[1970-01-01T00:56:32.442Z] [INFO] MQTT configured
[2022-04-27T06:57:35.003Z] [INFO] Successfully set the robot time via NTP to 2022-04-27T06:57:35.898Z
[2022-04-27T06:57:40.917Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:57:40.921Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:57:46.293Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:57:46.297Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:57:51.808Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:57:51.812Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:57:57.429Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:57:57.433Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:58:02.950Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:58:02.954Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:58:08.263Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:58:08.271Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:58:13.732Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:58:13.736Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:58:19.227Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:58:19.231Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:58:24.734Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:58:24.738Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:58:30.243Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:58:30.247Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:58:31.742Z] [WARN] Unable to reach vacuum. Giving up after 100 tries
[2022-04-27T06:58:31.752Z] [ERROR] unhandledRejection {
  reason: RetryWrapperSurrenderError [MiioTimeoutError]: request timed out:{"method":"get_properties","params":[{"siid":4,"piid":2,"did":520954959},{"siid":4,"piid":3,"did":520954959}],"id":102104}
      at RetryWrapper.retryHandshakeHelper (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:181:19)
      at doRetry (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:130:22)
      at /snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:148:25,
  stack: 'MiioTimeoutError: request timed out:{"method":"get_properties","params":[{"siid":4,"piid":2,"did":520954959},{"siid":4,"piid":3,"did":520954959}],"id":102104}\n' +
    '    at RetryWrapper.retryHandshakeHelper (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:181:19)\n' +
    '    at doRetry (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:130:22)\n' +
    '    at /snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:148:25',
  promise: Promise {
    <rejected> RetryWrapperSurrenderError [MiioTimeoutError]: request timed out:{"method":"get_properties","params":[{"siid":4,"piid":2,"did":520954959},{"siid":4,"piid":3,"did":520954959}],"id":102104}
        at RetryWrapper.retryHandshakeHelper (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:181:19)
        at doRetry (/snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:130:22)
        at /snapshot/Valetudo/backend/lib/miio/RetryWrapper.js:148:25
  }
}
[2022-04-27T06:58:37.261Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:58:37.265Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:58:42.766Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:58:42.770Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:58:48.266Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:58:48.278Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:58:53.775Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:58:53.779Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:58:59.283Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:58:59.287Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:59:04.791Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:59:04.795Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:59:10.296Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:59:10.299Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:59:15.800Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:59:15.809Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:59:21.308Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:59:21.312Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:59:26.816Z] [INFO] Got an expired token. Changing to new
[2022-04-27T06:59:26.820Z] [INFO] Got token from handshake: 3154376e32764147647644756e647375
[2022-04-27T06:59:28.310Z] [WARN] Unable to reach vacuum. Giving up after 100 tries
```

**Comment by Hypfer** [comment]
Please follow the correct install procedure as documented on valetudo.cloud

The issues you're seeing are usually caused by the robot not being joined to the Wi-Fi Network by Valetudo but instead through some other means.
