### ISSUE TITLE
Dreame D9 crash shortly after starting a cleaning with firmware 1132

### ISSUE THREAD

**Issue by Araly** [Hypfer/Valetudo#1561]
## Describe the bug

When I start the cleaning (either by pressing the physical center button or by pressing the start button in the Valetudo interface), the robot starts cleaning for ~30 seconds, and then stops. The vaccuming stops, the robot itself stops moving, and the lights start flashing. While I was getting the logs from the robot, at some point (several minutes after) the lights started flashing red, and the voice said there was an issue with the left wheel. I don't think there's an issue with the left wheel.

*/tmp/valetudo.log*
~~~
[1970-01-01T00:00:31.318Z] [INFO] Set Logfile to /tmp/valetudo.log
[1970-01-01T00:00:31.346Z] [INFO] Autodetected DreameD9ValetudoRobot
[1970-01-01T00:00:31.543Z] [INFO] Starting Valetudo 2022.08.0
[1970-01-01T00:00:31.545Z] [INFO] Commit ID: 214b5c0c11c0cf70fa56ff915fda05e064a18355
[1970-01-01T00:00:31.546Z] [INFO] Configuration file: /data/valetudo_config.json
[1970-01-01T00:00:31.547Z] [INFO] Logfile: /tmp/valetudo.log
[1970-01-01T00:00:31.549Z] [INFO] Robot: Dreame D9 (DreameD9ValetudoRobot)
[1970-01-01T00:00:31.549Z] [INFO] JS Runtime Version: v18.5.0-Valetudo
[1970-01-01T00:00:31.550Z] [INFO] Arch: arm
[1970-01-01T00:00:31.553Z] [INFO] Max Heap Size: 34 MiB
[1970-01-01T00:00:31.553Z] [INFO] Node Flags: --expose-gc --max-heap-size=34 --optimize-for-size --lite-mode --no-regexp-tier-up --no-expose-wasm
[1970-01-01T00:00:31.572Z] [INFO] Autogenerated System ID: ExcellentFirmCrocodile
[1970-01-01T00:00:31.577Z] [INFO] DeviceId 447443411
[1970-01-01T00:00:31.578Z] [INFO] IP 127.0.0.1
[1970-01-01T00:00:31.578Z] [INFO] CloudSecret 1jLrudFUZqMMXChT
[1970-01-01T00:00:31.579Z] [INFO] LocalSecret 5995Y0e7FHpZNqFP
[1970-01-01T00:00:31.582Z] [INFO] Firmware Version: 1132
[1970-01-01T00:00:31.582Z] [INFO] MCU Version: 0.9.3
[1970-01-01T00:00:31.589Z] [INFO] Current rootfs: rootfs2 (/dev/nand0p6)
[1970-01-01T00:00:32.013Z] [INFO] Valetudo can be reached via: valetudo-excellentfirmcrocodile.local
[1970-01-01T00:00:48.654Z] [INFO] Setting /proc/self/oom_score_adj to 666. Previous value: 0
[1970-01-01T00:00:48.676Z] [INFO] Dummycloud is spoofing 127.0.0.1:8053 on 127.0.0.1:8053
[1970-01-01T00:00:48.692Z] [INFO] Webserver running on port 80
[1970-01-01T00:00:48.701Z] [INFO] FDSMockServer running on port 8079
[1970-01-01T00:00:48.726Z] [INFO] Bonjour service "Valetudo ExcellentFirmCrocodile Web" with type "http" started
[1970-01-01T00:00:48.728Z] [INFO] Bonjour service "Valetudo ExcellentFirmCrocodile" with type "valetudo" started
[1970-01-01T00:01:01.245Z] [INFO] Dummycloud connected
[1970-01-01T00:01:02.051Z] [INFO] Network state changed
[1970-01-01T00:01:02.053Z] [INFO] Restarting NetworkAdvertisementManager
[1970-01-01T00:01:02.088Z] [INFO] Valetudo can be reached via: valetudo-excellentfirmcrocodile.local
[1970-01-01T00:01:02.119Z] [INFO] Bonjour service "Valetudo ExcellentFirmCrocodile Web" with type "http" started
[1970-01-01T00:01:02.120Z] [INFO] Bonjour service "Valetudo ExcellentFirmCrocodile" with type "valetudo" started
[2022-08-24T10:30:02.004Z] [INFO] Successfully set the robot time via NTP to 2022-08-24T10:30:02.901Z
[2022-08-24T10:30:19.917Z] [INFO] Cloud message timed out. Assuming that we're not connected anymore
[2022-08-24T10:30:19.920Z] [WARN] Error while polling map MiioTimeoutError: request timed out:{"method":"action","params":{"did":447443411,"siid":6,"aiid":1,"in":[{"piid":2,"value":"{\"frame_type\":\"I\", \"force_type\": 1, \"req_type\": 1}"}]},"id":2}
    at Object.onTimeoutCallback (/snapshot/Valetudo/backend/lib/miio/MiioSocket.js:201:32)
    at Timeout._onTimeout (/snapshot/Valetudo/backend/lib/miio/MiioSocket.js:207:53)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[2022-08-24T10:30:29.720Z] [INFO] Dummycloud connected
[2022-08-24T10:30:40.222Z] [INFO] Cloud message timed out. Assuming that we're not connected anymore
[2022-08-24T10:30:40.223Z] [WARN] Error while polling map MiioTimeoutError: request timed out:{"method":"action","params":{"did":447443411,"siid":6,"aiid":1,"in":[{"piid":2,"value":"{\"frame_type\":\"I\", \"force_type\": 1, \"req_type\": 1}"}]},"id":3}
    at Object.onTimeoutCallback (/snapshot/Valetudo/backend/lib/miio/MiioSocket.js:201:32)
    at Timeout._onTimeout (/snapshot/Valetudo/backend/lib/miio/MiioSocket.js:207:53)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[2022-08-24T10:30:49.720Z] [INFO] Dummycloud connected
[2022-08-24T10:31:00.223Z] [INFO] Cloud message timed out. Assuming that we're not connected anymore
[2022-08-24T10:31:00.224Z] [WARN] Error while polling map MiioTimeoutError: request timed out:{"method":"action","params":{"did":447443411,"siid":6,"aiid":1,"in":[{"piid":2,"value":"{\"frame_type\":\"I\", \"force_type\": 1, \"req_type\": 1}"}]},"id":4}
    at Object.onTimeoutCallback (/snapshot/Valetudo/backend/lib/miio/MiioSocket.js:201:32)
    at Timeout._onTimeout (/snapshot/Valetudo/backend/lib/miio/MiioSocket.js:207:53)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)
[2022-08-24T10:31:05.198Z] [INFO] Dummycloud connected
[2022-08-24T10:38:39.946Z] [INFO] Network state changed
[2022-08-24T10:38:39.947Z] [INFO] Restarting NetworkAdvertisementManager
[2022-08-24T10:38:39.961Z] [INFO] Valetudo can be reached via: valetudo-excellentfirmcrocodile.local
[2022-08-24T10:38:39.982Z] [INFO] Bonjour service "Valetudo ExcellentFirmCrocodile Web" with type "http" started
[2022-08-24T10:38:39.983Z] [INFO] Bonjour service "Valetudo ExcellentFirmCrocodile" with type "valetudo" started
[2022-08-24T10:41:09.984Z] [INFO] Network state changed
[2022-08-24T10:41:09.985Z] [INFO] Restarting NetworkAdvertisementManager
[2022-08-24T10:41:09.997Z] [INFO] Valetudo can be reached via: valetudo-excellentfirmcrocodile.local
[2022-08-24T10:41:10.014Z] [INFO] Bonjour service "Valetudo ExcellentFirmCrocodile Web" with type "http" started
[2022-08-24T10:41:10.014Z] [INFO] Bonjour service "Valetudo ExcellentFirmCrocodile" with type "valetudo" started
[2022-08-24T10:41:41.844Z] [INFO] Cloud message timed out. Assuming that we're not connected anymore
[2022-08-24T10:41:41.846Z] [WARN] Error while polling map MiioTimeoutError: request timed out:{"method":"action","params":{"did":447443411,"siid":6,"aiid":1,"in":[{"piid":2,"value":"{\"frame_type\":\"I\", \"force_type\": 1, \"req_type\": 1}"}]},"id":23}
    at Object.onTimeoutCallback (/snapshot/Valetudo/backend/lib/miio/MiioSocket.js:201:32)
    at Timeout._onTimeout (/snapshot/Valetudo/backend/lib/miio/MiioSocket.js:207:53)
    at listOnTimeout (node:internal/timers:564:17)
    at process.processTimers (node:internal/timers:507:7)

~~~

## To Reproduce

1. Follow instructions on https://valetudo.cloud/pages/general/rooting-instructions.html for Dreame D9
2. Connect to robot's wifi, and give it the password for the router
3. Let the robot connect to the router's wifi
4. After a while, the router finally sees the robot and the interface slowly loads up
5. Start a cleaning
6. Wait a bit
7. See that the robot stops and lights flash.

or instead of 2 to 5, you can also just click on the button to start a cleaning, and the robot will also stop and lights will flash shortly after the cleaning starts.

### Vacuum Model
Dreame D9

### Valetudo Version
2022.08.0

### Firmware Version
1135

## Expected behavior

The robot is able to start and finish a cleaning without stopping.

## Additional context

This seems similar to https://github.com/Hypfer/Valetudo/issues/1165 and in that case the solution found was to upgrade to firmware version 1100, but I use a version 1132 that's even more recent.

I don't know if it's related, but it's been very difficult for me to even reach the Valetudo interface. I would connect to wifi, but the router wouldn't see it. I had to reboot and give the robot the password to the router's wifi a couple times before I was able to reach the UI. And even when I reached it, it was very slow. The map took a while to appear, and a lot of the things were not available. For example I couldn't see the running firmware or Valetudo versions, maybe the battery level was also missing for a while, but it ended up appearing with the map.

Is there another place where I can ask for help also ? I couldn't find a Matrix room, or a Discord/Revolt server. I guess I should also report an issue for https://builder.dontvacuum.me/_dreame_p2009.html but I couldn't find a repository for the Dreame D9 to write an issue in.

**Comment by Araly** [comment]
updating the MCU did the trick.

I'll try to write a PR so it's at least mentioned in the instructions for rooting
