### ISSUE TITLE
Roborock S5 - MQTT - Failed to parse Value to be sent for topic

### ISSUE THREAD

**Issue by RandomLegend** [Hypfer/Valetudo#1936]
## Describe the bug

Logs in my freshly installed Valetudo spam this  Error multiple times a second:

`
Failed to parse value to be sent for topic valetudo/MeatyFearfulBaboon/FanSpeedControlCapability/preset: Error: Value 'custom' is invalid for enum with format [low,medium,high,max,off]!
    at PropertyMqttHandle.marshalHomie (/snapshot/Valetudo/backend/lib/mqtt/handles/MqttHandle.js:371:27)
    at PropertyMqttHandle.getHomie (/snapshot/Valetudo/backend/lib/mqtt/handles/MqttHandle.js:298:29)
    at async MqttController.refresh (/snapshot/Valetudo/backend/lib/mqtt/MqttController.js:716:23)
    at async PropertyMqttHandle.refresh (/snapshot/Valetudo/backend/lib/mqtt/handles/MqttHandle.js:237:9)
    at async PresetSelectionCapabilityMqttHandle.refresh (/snapshot/Valetudo/backend/lib/mqtt/handles/MqttHandle.js:240:13)`

I checked the MQTT Settings and disabled Homie because i use Home Assistant. But despite disabling it, restarting the robot and even restarting the whole MQTT connection, it still spams the logs with it.

### Screenshots

![image](https://github.com/Hypfer/Valetudo/assets/38812603/2960d945-973e-484c-8e6e-2aeb115cb82b)

### Vacuum Model

Roborock S5

### Valetudo Version

2023.10.0

**Comment by Hypfer** [comment]
https://github.com/Hypfer/Valetudo/discussions/1807
