### ISSUE TITLE
Home Assistant auto configuration not working with latest version

### ISSUE THREAD

**Issue by r1sim** [Hypfer/Valetudo#260]
Home assistant seems to have some difficulties with the latest valetudo version. I get the following error after my home assistant instance discovers the robot:
```hass_1  | 2019-06-09 23:47:00 INFO (MainThread) [homeassistant.components.mqtt.discovery] Found new component: vacuum valetudo_rockrobo
hass_1  | 2019-06-09 23:47:00 ERROR (MainThread) [homeassistant.components.mqtt.vacuum] Exception in async_discover when dispatching 'mqtt_discovery_new_vacuum_mqtt': ({'name': 'rockrobo', 'schema': 'state', 'supported_features': ['start', 'pause', 'stop', 'return_home', 'battery', 'status', 'locate', 'clean_spot', 'fan_speed', 'send_command'], 'command_topic': 'valetudo/rockrobo/command', 'state_topic': 'valetudo/rockrobo/state', 'set_fan_speed_topic': 'valetudo/rockrobo/set_fan_speed', 'fan_speed_list': ['min', 'medium', 'high', 'max', 'mop'], 'send_command_topic': 'valetudo/rockrobo/custom_command', 'json_attributes_topic': 'valetudo/rockrobo/attributes', 'platform': 'mqtt'},)
hass_1  | Traceback (most recent call last):
hass_1  |   File "/usr/src/app/homeassistant/helpers/config_validation.py", line 663, in __call__
hass_1  |     return super().__call__(data)
hass_1  |   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
hass_1  |     return self._compiled([], data)
hass_1  |   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
hass_1  |     return base_validate(path, iteritems(data), out)
hass_1  |   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
hass_1  |     raise er.MultipleInvalid(errors)
hass_1  | voluptuous.error.MultipleInvalid: extra keys not allowed @ data['schema']
hass_1  | 
hass_1  | During handling of the above exception, another exception occurred:
hass_1  | 
hass_1  | Traceback (most recent call last):
hass_1  |   File "/usr/src/app/homeassistant/components/mqtt/vacuum.py", line 156, in async_discover
hass_1  |     config = PLATFORM_SCHEMA(discovery_payload)
hass_1  |   File "/usr/src/app/homeassistant/helpers/config_validation.py", line 675, in __call__
hass_1  |     validated = super().__call__(data)
hass_1  |   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 267, in __call__
hass_1  |     return self._compiled([], data)
hass_1  |   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 589, in validate_dict
hass_1  |     return base_validate(path, iteritems(data), out)
hass_1  |   File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 427, in validate_mapping
hass_1  |     raise er.MultipleInvalid(errors)
hass_1  | voluptuous.error.MultipleInvalid: value is not allowed @ data['supported_features'][0]
```

The auto configuration works perfectly fine when i'm using valetudo 0.3.1. I guess there is an issue with the mqtt message in "_homeassistant/vacuum/valetudo_rockrobo/config_" which has changed quite a bit. 

Version 0.3.1:
```
{"name":"rockrobo","supported_features":["turn_on","pause","stop","return_home","battery","status","locate","clean_spot","fan_speed","send_command"],"command_topic":"valetudo/rockrobo/command","battery_level_topic":"valetudo/rockrobo/state","battery_level_template":"{{ value_json.battery_level }}","charging_topic":"valetudo/rockrobo/state","charging_template":"{{value_json.charging}}","cleaning_topic":"valetudo/rockrobo/state","cleaning_template":"{{value_json.cleaning}}","docked_topic":"valetudo/rockrobo/state","docked_template":"{{value_json.docked}}","error_topic":"valetudo/rockrobo/state","error_template":"{{value_json.error}}","fan_speed_topic":"valetudo/rockrobo/state","fan_speed_template":"{{ value_json.fan_speed }}","set_fan_speed_topic":"valetudo/rockrobo/set_fan_speed","fan_speed_list":["min","medium","high","max"],"send_command_topic":"valetudo/rockrobo/custom_command","json_attributes_topic":"valetudo/rockrobo/attributes"}
```

Current version from git:
```
{"name":"rockrobo","schema":"state","supported_features":["start","pause","stop","return_home","battery","status","locate","clean_spot","fan_speed","send_command"],"command_topic":"valetudo/rockrobo/command","state_topic":"valetudo/rockrobo/state","set_fan_speed_topic":"valetudo/rockrobo/set_fan_speed","fan_speed_list":["min","medium","high","max","mop"],"send_command_topic":"valetudo/rockrobo/custom_command","json_attributes_topic":"valetudo/rockrobo/attributes"}
```

Some additional information:
- I use home assistant version 0.92.2 running on docker.
- My mqtt broker is mosquitto also running on docker.
- I used the roborock S50

**Comment by Hypfer** [comment]
Yeah there are incompatibilities. The latest master requires at least HA 0.93

https://github.com/Hypfer/Valetudo/pull/178#issuecomment-486650867
