### ISSUE TITLE
OOM issues on flaky wifi connections

### ISSUE THREAD

**Issue by Hypfer** [Hypfer/Valetudo#556]
## Describe the bug

Valetudo sometimes goes out of memory if the wifi connection is flaky.

## To Reproduce

Use shitty Wifi access Points without 802.11r in some large building with thick walls

### Vacuum Model

Roborock S5

### Valetudo Version

0.5.3

### Firmware Version

2020

## Additional context

<details>
<summary>Log A: Almost OOM</summary>

```
unhandledRejection TimeoutError: request timed out:{"method":"get_status","params":{},"id":4267}
    at Timeout.timeout [as _onTimeout] (/snapshot/Valetudo/lib/miio/MiioSocket.js:164:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[2020-07-09T12:07:53.391Z] [INFO] Connected successfully to mqtt server
[2020-07-09T12:07:53.833Z] [INFO] Memory Stats {
  totalHeapSize: '30.949 MiB',
  mallocedMemory: '0.008 MiB',
  peakMallocedMemory: '2.297 MiB'
}
[2020-07-09T12:08:03.834Z] [INFO] Memory Stats {
  totalHeapSize: '30.949 MiB',
  mallocedMemory: '0.008 MiB',
  peakMallocedMemory: '2.297 MiB'
}
```

</details>
<details>
<summary>Log B: Lots of timeout errors on the cloud interface</summary>

```
[2020-07-09T12:14:43.957Z] [INFO] Memory Stats {
  totalHeapSize: '18.809 MiB',
  mallocedMemory: '0.008 MiB',
  peakMallocedMemory: '2.297 MiB'
}
unhandledRejection TimeoutError: request timed out:{"method":"get_status","params":{},"id":5340}
    at Timeout.timeout [as _onTimeout] (/snapshot/Valetudo/lib/miio/MiioSocket.js:164:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
unhandledRejection TimeoutError: request timed out:{"method":"get_status","params":{},"id":5341}
    at Timeout.timeout [as _onTimeout] (/snapshot/Valetudo/lib/miio/MiioSocket.js:164:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[2020-07-09T12:14:53.965Z] [INFO] Memory Stats {
  totalHeapSize: '18.809 MiB',
  mallocedMemory: '0.008 MiB',
  peakMallocedMemory: '2.297 MiB'
}
unhandledRejection TimeoutError: request timed out:{"method":"get_status","params":{},"id":5343}
    at Timeout.timeout [as _onTimeout] (/snapshot/Valetudo/lib/miio/MiioSocket.js:164:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
unhandledRejection TimeoutError: request timed out:{"method":"get_status","params":{},"id":5344}
    at Timeout.timeout [as _onTimeout] (/snapshot/Valetudo/lib/miio/MiioSocket.js:164:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
unhandledRejection TimeoutError: request timed out:{"method":"get_status","params":{},"id":5345}
    at Timeout.timeout [as _onTimeout] (/snapshot/Valetudo/lib/miio/MiioSocket.js:164:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[2020-07-09T12:15:03.962Z] [INFO] Memory Stats {
  totalHeapSize: '18.809 MiB',
  mallocedMemory: '0.008 MiB',
  peakMallocedMemory: '2.297 MiB'
}
unhandledRejection TimeoutError: request timed out:{"method":"get_status","params":{},"id":5346}
    at Timeout.timeout [as _onTimeout] (/snapshot/Valetudo/lib/miio/MiioSocket.js:164:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
unhandledRejection TimeoutError: request timed out:{"method":"get_status","params":{},"id":5347}
    at Timeout.timeout [as _onTimeout] (/snapshot/Valetudo/lib/miio/MiioSocket.js:164:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
[2020-07-09T12:15:13.963Z] [INFO] Memory Stats {
  totalHeapSize: '19.059 MiB',
  mallocedMemory: '0.008 MiB',
  peakMallocedMemory: '2.297 MiB'
}
unhandledRejection TimeoutError: request timed out:{"method":"get_status","params":{},"id":5348}
    at Timeout.timeout [as _onTimeout] (/snapshot/Valetudo/lib/miio/MiioSocket.js:164:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
unhandledRejection TimeoutError: request timed out:{"method":"get_status","params":{},"id":5349}
    at Timeout.timeout [as _onTimeout] (/snapshot/Valetudo/lib/miio/MiioSocket.js:164:32)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

```

</details>

**Comment by Hypfer** [comment]
Might be resolved with the switch to SSE instead of WebSockets
