### ISSUE TITLE
MQTT doesn't work sometimes after Valetudo start

### ISSUE THREAD

**Issue by definitio** [Hypfer/Valetudo#918]
## Describe the bug

Vacuum can be unavailable or only one topic is published regulary (last time - `vacuum_sensor_WifiConfigurationCapability`) after Valetudo start.

## To Reproduce

1. Wait until vacuum reboot (my vacuum reboots every night) or reboot it manually.
2. If MQTT works - try again.

### Vacuum Model

Gen 1

### Valetudo Version

2021.04.0

## Additional context

<details>
<summary>Log</summary>

```
[2021-05-11T00:52:52.792Z] [INFO] Loading configuration file: /mnt/data/valetudo/valetudo_config.json
[2021-05-11T00:52:52.824Z] [INFO] Set Logfile to /tmp/valetudo.log
[2021-05-11T00:52:52.835Z] [INFO] Autodetected RoborockV1ValetudoRobot
[2021-05-11T00:52:53.069Z] [INFO] Starting Valetudo 2021.04.0
[2021-05-11T00:52:53.071Z] [INFO] Commit ID: 7d28ac85cea7a4081f49fe199f19adf678778f78
[2021-05-11T00:52:53.072Z] [INFO] Configuration file: /mnt/data/valetudo/valetudo_config.json
[2021-05-11T00:52:53.074Z] [INFO] Logfile: /tmp/valetudo.log
[2021-05-11T00:52:53.075Z] [INFO] Robot: Beijing Roborock Technology Co., Ltd. Xiaomi Mi Robot Vacuum (RoborockV1ValetudoRobot)
[2021-05-11T00:52:53.076Z] [INFO] JS Runtime Version: v14.16.1
[2021-05-11T00:52:53.077Z] [INFO] Arch: arm
[2021-05-11T00:52:53.079Z] [INFO] Max Heap Size: 34 MiB
[2021-05-11T00:52:53.080Z] [INFO] Node Flags: --expose-gc --max-heap-size=34
[2021-05-11T00:52:53.092Z] [INFO] DeviceId 259770451
[2021-05-11T00:52:53.093Z] [INFO] IP 127.0.0.1
[2021-05-11T00:52:53.094Z] [INFO] CloudSecret xxx
[2021-05-11T00:52:53.096Z] [INFO] LocalSecret xxx
[2021-05-11T00:52:53.636Z] [INFO] Dummycloud is spoofing 127.0.0.1:8053 on 127.0.0.1:8053
[2021-05-11T00:52:53.646Z] [INFO] Webserver running on port [33m80[39m
[2021-05-11T00:52:53.666Z] [INFO] Map Upload Server running on port 8079
[2021-05-11T00:52:58.655Z] [WARN] Error during time sync: Error: getaddrinfo EAI_AGAIN time.lan
[90m    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)[39m {
  errno: [33m-3001[39m,
  code: [32m'EAI_AGAIN'[39m,
  syscall: [32m'getaddrinfo'[39m,
  hostname: [32m'time.lan'[39m
}
[2021-05-11T00:52:59.819Z] [INFO] Connected successfully to MQTT broker
[2021-05-11T00:53:00.550Z] [INFO] Cloud connected
[2021-05-11T00:53:00.915Z] [INFO] MQTT configured
[2021-05-11T00:53:00.984Z] [WARN] MQTT handle home/vacuum/MapData failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at MapNodeMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:00.993Z] [WARN] MQTT handle home/vacuum/FanSpeedControlCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at IntensityPresetCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at IntensityPresetCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:00.997Z] [WARN] MQTT handle home/vacuum/BasicControlCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at BasicControlCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at BasicControlCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.001Z] [WARN] MQTT handle home/vacuum/ConsumableMonitoringCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at ConsumableMonitoringCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at ConsumableMonitoringCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.005Z] [WARN] MQTT handle home/vacuum/ZoneCleaningCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at ZoneCleaningCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at ZoneCleaningCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.009Z] [WARN] MQTT handle home/vacuum/GoToLocationCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at GoToLocationCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at GoToLocationCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.013Z] [WARN] MQTT handle home/vacuum/WifiConfigurationCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at WifiConfigurationCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at WifiConfigurationCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.017Z] [WARN] MQTT handle home/vacuum/LocateCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at LocateCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at LocateCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.021Z] [WARN] MQTT handle home/vacuum/StatusStateAttribute failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at StatusStateMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at StatusStateMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.024Z] [WARN] MQTT handle home/vacuum/BatteryStateAttribute failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at BatteryStateMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at BatteryStateMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.036Z] [WARN] MQTT handle home/vacuum/MapData failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at MapNodeMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.039Z] [WARN] MQTT handle home/vacuum/FanSpeedControlCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at IntensityPresetCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at IntensityPresetCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.042Z] [WARN] MQTT handle home/vacuum/BasicControlCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at BasicControlCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at BasicControlCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.045Z] [WARN] MQTT handle home/vacuum/ConsumableMonitoringCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at ConsumableMonitoringCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at ConsumableMonitoringCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.049Z] [WARN] MQTT handle home/vacuum/ZoneCleaningCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at ZoneCleaningCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at ZoneCleaningCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.052Z] [WARN] MQTT handle home/vacuum/GoToLocationCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at GoToLocationCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at GoToLocationCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.055Z] [WARN] MQTT handle home/vacuum/WifiConfigurationCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at WifiConfigurationCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at WifiConfigurationCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.058Z] [WARN] MQTT handle home/vacuum/LocateCapability failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at LocateCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at LocateCapabilityMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.061Z] [WARN] MQTT handle home/vacuum/StatusStateAttribute failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at StatusStateMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at StatusStateMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:01.064Z] [WARN] MQTT handle home/vacuum/BatteryStateAttribute failed to configure Error: Handle may only be configured while the MQTT controller is not initialized
    at BatteryStateMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:160:19)
    at BatteryStateMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/RobotStateNodeMqttHandle.js:30:21)
    at RobotMqttHandle.configure (/snapshot/Valetudo/lib/mqtt/handles/MqttHandle.js:167:29)
[90m    at processTicksAndRejections (internal/process/task_queues.js:93:5)[39m
    at async /snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:110:13
    at async MqttController.reconfigure (/snapshot/Valetudo/lib/mqtt/MqttController.js:497:13)
    at async RobotMqttHandle.onStatusAttributeEvent (/snapshot/Valetudo/lib/mqtt/handles/RobotMqttHandle.js:97:9)
[2021-05-11T00:53:59.004Z] [INFO] Successfully set the robot time via NTP to [35m2021-05-11T00:53:59.891Z[39m
[2021-05-11T08:00:02.791Z] [WARN] Failed to parse uploaded map
[2021-05-11T08:00:04.790Z] [WARN] Failed to parse uploaded map
[2021-05-11T08:06:23.972Z] [INFO] Cloud message timed out. Assuming that we're not connected anymore
[2021-05-11T08:06:41.749Z] [INFO] Cloud connected
[2021-05-11T08:13:23.975Z] [INFO] Cloud message timed out. Assuming that we're not connected anymore
[2021-05-11T08:13:42.476Z] [INFO] Cloud connected
[2021-05-11T08:15:05.791Z] [INFO] Cloud message timed out. Assuming that we're not connected anymore
[2021-05-11T08:15:23.176Z] [INFO] Cloud connected
[2021-05-11T08:24:45.515Z] [INFO] Cloud message timed out. Assuming that we're not connected anymore
[2021-05-11T08:25:03.951Z] [INFO] Cloud connected
[2021-05-11T08:25:04.402Z] [INFO] Cloud message timed out. Assuming that we're not connected anymore
[2021-05-11T08:25:04.773Z] [INFO] Cloud connected
```
</details>

**Comment by Depau** [comment]
Can you test if it still occurs with current master?

**Comment by definitio** [comment]
The issue is not reproducible reliably with manual reboots. I will report in a few days.

**Comment by kquinsland** [comment]
I may be hitting this same issue. If not, i am more than happy to open a dedicated thread.

I can delete my vac from HA and reboot the device. After several seconds, I'll see a flurry of activity on the `homeassistant/#` and `valetudo/#` topics.  HA will then show 11 entities for my vac on the device registry, but each entity will be `Unavailable`.

I think this is due to the `availability_topic` that is being configured in the discovery messages.

For example:

topic: `homeassistant/sensor/rosie/rosie_sensor_error/config`

```json
{"state_topic":"valetudo/rosie/StatusStateAttribute/error","icon":"mdi:alert","name":"Error description","unique_id":"rosie_sensor_error","availability_topic":"valetudo/rosie/$state","payload_available":"ready","payload_not_available":"lost","availability_mode":"latest","device":{"manufacturer":"Beijing Roborock Technology Co., Ltd.","model":"S6","name":"rosie","identifiers":["rosie"],"sw_version":"2021.04.0 (Valetudo)"}}
```

I do not see _any_ messages on my MQTT broker under the `valetudo/rosie/$state` topic, though.


Is this the same issue that @definitio can  no longer reproduce or should I open a new ticket?

**Comment by Depau** [comment]
> I may be hitting this same issue. If not, i am more than happy to open a dedicated thread.
> 
> I can delete my vac from HA and reboot the device. After several seconds, I'll see a flurry of activity on the `homeassistant/#` and `valetudo/#` topics. HA will then show 11 entities for my vac on the device registry, but each entity will be `Unavailable`.
> 
> I think this is due to the `availability_topic` that is being configured in the discovery messages.
> 
> For example:
> 
> topic: `homeassistant/sensor/rosie/rosie_sensor_error/config`
> 
> ```json
> {"state_topic":"valetudo/rosie/StatusStateAttribute/error","icon":"mdi:alert","name":"Error description","unique_id":"rosie_sensor_error","availability_topic":"valetudo/rosie/$state","payload_available":"ready","payload_not_available":"lost","availability_mode":"latest","device":{"manufacturer":"Beijing Roborock Technology Co., Ltd.","model":"S6","name":"rosie","identifiers":["rosie"],"sw_version":"2021.04.0 (Valetudo)"}}
> ```
> 
> I do not see _any_ messages on my MQTT broker under the `valetudo/rosie/$state` topic, though.
> 
> Is this the same issue that @definitio can no longer reproduce or should I open a new ticket?

IDK, you haven't shown any logs.

Both of you should try building from latest master and see if it still happens.

**Comment by definitio** [comment]
Latest works for 4 days without issues.
