### ISSUE TITLE
Disabling homeassistant breaks mqtt commands on 2021.04

### ISSUE THREAD

**Issue by jweiher** [Hypfer/Valetudo#930]
## Describe the bug

I tried controlling my s5 max with valetudo via mqtt (node red). When sending START / HOME via mqtt i noticed that nothing happened and after that the valetudo ui was unavailable. After some fiddling and starting valetudo in the foreground i noticed this stack trace:
```
[2021-05-16T14:34:08.761Z] [INFO] exiting with code 1...
[2021-05-16T14:34:08.765Z] [ERROR] Stacktrace that lead to the process exiting: Error
    at process.<anonymous> (/snapshot/Valetudo/index.js:35:70)
    at process.emit (events.js:315:20)
    at process._fatalException (internal/process/execution.js:170:19)
/snapshot/Valetudo/lib/mqtt/MqttController.js:322
                if (topic.startsWith(this.hassController.autoconfPrefix + "/") && message.toString().length > 0) {
                                                         ^

TypeError: Cannot read property 'autoconfPrefix' of null
    at MqttClient.<anonymous> (/snapshot/Valetudo/lib/mqtt/MqttController.js:322:58)
    at MqttClient.emit (events.js:315:20)
    at MqttClient._handlePublish (/snapshot/Valetudo/node_modules/mqtt/lib/client.js:1277:12)
    at MqttClient._handlePacket (/snapshot/Valetudo/node_modules/mqtt/lib/client.js:410:12)
    at work (/snapshot/Valetudo/node_modules/mqtt/lib/client.js:321:12)
    at Writable.writable._write (/snapshot/Valetudo/node_modules/mqtt/lib/client.js:335:5)
    at doWrite (/snapshot/Valetudo/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at writeOrBuffer (/snapshot/Valetudo/node_modules/readable-stream/lib/_stream_writable.js:398:5)
    at Writable.write (/snapshot/Valetudo/node_modules/readable-stream/lib/_stream_writable.js:307:11)
    at Socket.ondata (internal/streams/readable.js:719:22)
```
So i started looking for something like "autoconf" in the mqtt settings, then i remembered that i disabled the home assistant stuff. After enabling that again, all worked.

## To Reproduce
* Disable home assistant
* Send start/home/stop via mqtt (mosquitto_pub -h localhost -m "HOME" -t "valetudo/robot/BasicControlCapability/operation/set")
* See that UI is broken and valetudo is not running anymore on the ui.
* Validate the stacktrace via ` VALETUDO_CONFIG_PATH=/mnt/data/valetudo_config.json /mnt/data/valetudo`

### Vacuum Model
Roborock S5 Max

### Valetudo Version
2021.04

## Expected behavior
Well either everything working or at least a note when disabling home assistant. Everything but crashing would be great :)

**Comment by Hypfer** [comment]
Fixed with #912
